import { Injectable } from '@angular/core';

@Injectable()
export class TablesService {
  constructor() { }
  getDataConf() {
    return [
      {
        prop: 'id',
        name: 'Item',
        width: 70
      },
      {
        prop: 'nroguia',
        name: 'Guia de Remisión',
        sortable: true
      },
      {
        prop: 'fechaEmision',
        name: 'Fecha de Emisión'
      },
      {
        prop: 'nroLiq',
        name: 'Nro. de Liquid.'
      },
      {
        prop: 'ordenServicio',
        name: 'Nro Ord. Servicio'
      },
      {
        prop: 'remitente',
        name: 'Razón Soc. Rem'
      },
      {
        prop: 'destinatario',
        name: 'Razón Soc. Dest'
      },
      {
        prop: 'estado',
        name: 'Estado'
      },
      {
        prop: 'producto',
        name: 'Producto'
      },
      {
        prop: 'cantidad',
        name: 'Cantidad'
      },
      {
        prop: 'chofer',
        name: 'Chofer'
      },
      {
        prop: 'nroGuiaCliente',
        name: 'Guía Rem. Cliente'
      },
      {
        prop: 'fechaRecepcion',
        name: 'Fec. Recepción'
      }
    ];
  }
  getAll() {
    return [
      {
          "id": 172,
          "nroguia": "7889-4345654",
          "fechaEmision": "2018-10-09",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "78.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "9900-9900000",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 168,
          "nroguia": "4677-2457777",
          "fechaEmision": "2018-10-17",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "123.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "2323-12313123",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 170,
          "nroguia": "4444-3344555",
          "fechaEmision": "2018-10-16",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "133.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "1222-222222",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 167,
          "nroguia": "3456-2368888",
          "fechaEmision": "2018-10-16",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "243.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "2233-1223555",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 165,
          "nroguia": "3334-2346666",
          "fechaEmision": "2018-10-09",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "123.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "4567-1235566",
          "fechaRecepcion": "2018-10-18"
      },
      {
          "id": 169,
          "nroguia": "1233-8642344",
          "fechaEmision": "2018-10-16",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "123.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "2323-2344444",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 159,
          "nroguia": "1233-1212222",
          "fechaEmision": "2018-10-16",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "1212.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "1223-123133",
          "fechaRecepcion": "2018-10-19"
      },
      {
          "id": 171,
          "nroguia": "1231-4455667",
          "fechaEmision": "2018-10-09",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "12.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "3344-222222",
          "fechaRecepcion": "2018-10-19"
      },
      {
          "id": 166,
          "nroguia": "061-0009280",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 164,
          "nroguia": "061-0009279",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 155,
          "nroguia": "061-0009278",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 154,
          "nroguia": "061-0009277",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 153,
          "nroguia": "061-0009272",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 152,
          "nroguia": "061-0009271",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 151,
          "nroguia": "061-0009270",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 150,
          "nroguia": "061-0009269",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 149,
          "nroguia": "061-0009268",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 148,
          "nroguia": "061-0009267",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 147,
          "nroguia": "061-0009266",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 146,
          "nroguia": "061-0009264",
          "fechaEmision": "2018-10-01",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-10-24"
      },
      {
          "id": 145,
          "nroguia": "061-0009263",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 144,
          "nroguia": "061-0009262",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 143,
          "nroguia": "061-0009261",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 142,
          "nroguia": "061-0009260",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 141,
          "nroguia": "061-0009259",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 140,
          "nroguia": "021-0009256",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 139,
          "nroguia": "021-0009246",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 138,
          "nroguia": "021-0009245",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 137,
          "nroguia": "021-0009235",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 136,
          "nroguia": "021-0009234",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 135,
          "nroguia": "021-0009233",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 134,
          "nroguia": "021-0009232",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 133,
          "nroguia": "021-0009230",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 132,
          "nroguia": "021-0009229",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 131,
          "nroguia": "019-0009228",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "550.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "003-000023199",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 130,
          "nroguia": "019-0009227",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 128,
          "nroguia": "019-0009226",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 125,
          "nroguia": "019-0009225",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 122,
          "nroguia": "019-0009224",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 121,
          "nroguia": "019-0009223",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 119,
          "nroguia": "019-0009222",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 118,
          "nroguia": "009-0009222",
          "fechaEmision": "2018-09-23",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023123",
          "fechaRecepcion": "2018-09-24"
      },
      {
          "id": 157,
          "nroguia": "0061-1231312",
          "fechaEmision": "2018-10-16",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "1231.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "1231-12312313",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 163,
          "nroguia": "0056-0988999",
          "fechaEmision": "2018-10-17",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "12.00",
          "chofer": "DIEGODE LAS CASAS",
          "nroGuiaCliente": "3544-122333",
          "fechaRecepcion": "2018-10-20"
      },
      {
          "id": 5,
          "nroguia": "004-0009289",
          "fechaEmision": "2018-09-22",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "ANULADO",
          "producto": "",
          "cantidad": "400.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "003-000023233",
          "fechaRecepcion": "2018-09-25"
      },
      {
          "id": 110,
          "nroguia": "004-0009222",
          "fechaEmision": "2018-09-24",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023232",
          "fechaRecepcion": "2018-09-25"
      },
      {
          "id": 4,
          "nroguia": "003-0009588",
          "fechaEmision": "2018-09-22",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "",
          "cantidad": "400.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "003-000023233",
          "fechaRecepcion": "2018-09-25"
      },
      {
          "id": 3,
          "nroguia": "002-0009488",
          "fechaEmision": "2018-09-22",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "",
          "cantidad": "400.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "003-000023232",
          "fechaRecepcion": "2018-09-25"
      },
      {
          "id": 2,
          "nroguia": "002-0009388",
          "fechaEmision": "2018-09-24",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "",
          "cantidad": "500.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "003-000023232",
          "fechaRecepcion": "2018-09-25"
      },
      {
          "id": 1,
          "nroguia": "002-0009382",
          "fechaEmision": "2018-09-24",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "600.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "002-000023232",
          "fechaRecepcion": "2018-09-25"
      },
      {
          "id": 158,
          "nroguia": "0012-1232131",
          "fechaEmision": "2018-10-17",
          "nroLiq": "",
          "ordenServicio": "",
          "remitente": "MIXERCON S.A",
          "destinatario": "MIXERCON S.A",
          "estado": "REGISTRADO",
          "producto": "CEMENTO A GRANEL - TIPO1",
          "cantidad": "1231.00",
          "chofer": "CARLOSDE LAS CASAS",
          "nroGuiaCliente": "1232-2323233",
          "fechaRecepcion": "2018-10-17"
      }
  ]
  }

}
